- destination: syn22017882
- files:
    - id: syn22017882
      format: csv
      final_filename: neuropath_corr
      provenance: []
      destination: synid

    - id: syn25454540
      format: csv
      final_filename: srm_data