- destination: syn25905764
- datasets:
  - genetics_scores:
      files:
        - syn25575153: table
      final_format: json
      provenance:
        - syn25575153
      column_rename:
        ensg: ensenbl_gene_id
        gene_name: hgnc_gene_id
      destination: syn25905764

  - neuropath_corr:
      files:
        - syn22017882: csv
      final_format: json
      provenance:
        - syn22017882
      column_rename:
        ensg: ensembl_gene_id
        gname: hgnc_gene_id
      destination: syn25905764

  - omics_scores:
      files:
        - syn22758536: table
      final_format: json
      provenance:
        - syn22758536
      destination: syn25905764

  - proteomics:
      files:
        - syn18689335: csv
      final_format: json
      provenance:
        - syn18689335
      column_rename:
        genename: hgnc_gene_id
        ensg: ensemble_gene_id
      destination: syn25905764

  - target_exp_validation_harmonized:
      files:
        - syn24184512: csv
      final_format: json
      provenance:
        - syn24184512
      destination: syn25905764

  - srm_data:
      files:
        - syn25454540: csv
      final_format: json
      provenance:
        - syn25454540
      destination: syn25905764

  - neuropath_corr:
      files:
        - syn22017882: csv
      final_format: json
      provenance:
        - syn22017882
      column_rename:
        ensg: ensembl_gene_id
        gname: hgnc_gene_id
      destination: syn25905764

  - team_info:
      files:
        - syn12615624: csv
        - syn12615633: csv
      final_format: json
      custom_transformations: 1
      provenance:
        - syn12615624
        - syn12615633
      destination: syn25905764

  - overall_scores:
      files:
        - syn25575156: table
      final_format: json
      custom_transformations: 1
      column_rename:
        genename: hgnc_gene_id
      provenance:
        - syn25575156
        - syn25575153
        - syn22758536
      destination: syn25905764

  - rnaseq_differential_expression:
      files:
        - syn14237651: tsv
        - syn25953363: feather
        - syn12540368: csv
        - syn12514912: csv
      final_format: json
      custom_transformations:
        models_to_keep:
            - Diagnosis AD-CONTROL ALL
            - Diagnosis.AOD AD-CONTROL ALL
            - Diagnosis.Sex AD-CONTROL FEMALE
            - Diagnosis.Sex AD-CONTROL MALE
        adjusted_p_value_threshold: 1
      provenance:
        - syn14237651
        - syn25953363
        - syn25953353
        - syn12540368
        - syn12514912
      destination: syn25905764

  - metabolomics:
      files:
        - syn26064497: feather
      final_format: json
      provenance:
        - syn19001410
        - syn26064497
      destination: syn25905764

  - network:
      files:
        - syn11685347: csv
        - syn25953363: feather
      final_format: json
      custom_transformations: 1
      provenance:
        - syn11685347
        - syn25953363
        - syn14237651
      destination: syn25905764
