- destination: &dest syn12177492
- staging_path: ./staging
- datasets:
    - biodomain_info:
        files:
          - name: genes_biodomains
            id: syn44151254.1
            format: csv
        final_format: json
        custom_transformations: 1
        provenance:
          - syn44151254.1
        column_rename:
          biodomain: name
        destination: *dest

    - genes_biodomains:
        files:
          - name: genes_biodomains
            id: syn44151254.1
            format: csv
        final_format: json
        custom_transformations: 1
        provenance:
          - syn44151254.1
        column_rename:
          ensembl_id: ensembl_gene_id
          goterm_name: go_terms
        destination: *dest

    - neuropath_corr:
        files:
          - name: neuropath_regression_results
            id: syn22017882.5
            format: csv
        final_format: json
        provenance:
          - syn22017882.5
        column_rename:
          ensg: ensembl_gene_id
          gname: hgnc_gene_id
        agora_rename:
          ensembl_gene_id: ensg
          hgnc_gene_id: gname
        destination: *dest

    - proteomics:
        files:
          - name: agora_proteomics
            id: syn18689335.3
            format: csv
        final_format: json
        provenance:
          - syn18689335.3
        column_rename:
          genename: hgnc_symbol
          ensg: ensembl_gene_id
        destination: *dest

    - proteomics_tmt:
        files:
          - name: agora_proteomics_tmt
            id: syn35221005.2
            format: csv
        final_format: json
        provenance:
          - syn35221005.2
        column_rename:
          genename: hgnc_symbol
          ensg: ensembl_gene_id
        destination: *dest

    - proteomics_srm:
        files:
          - name: agora_proteomics_srm
            id: syn52579640.3
            format: csv
        final_format: json
        provenance:
          - syn52579640.3
        column_rename:
          genename: hgnc_symbol
          ensg: ensembl_gene_id
        destination: *dest

    - target_exp_validation_harmonized:
        files:
          - name: target_exp_validation_harmonized
            id: syn24184512.6
            format: csv
        final_format: json
        provenance:
          - syn24184512.6
        destination: *dest

    - metabolomics:
        files:
          - name: metabolomics
            id: syn26064497.1
            format: feather
        final_format: json
        provenance:
          - syn26064497.1
        destination: *dest
        gx_folder: syn52948669

    - gene_info:
        files:
          - name: gene_metadata
            id: syn25953363.6
            format: feather
          - name: igap
            id: syn12514826.5
            format: csv
          - name: eqtl
            id: syn12514912.3
            format: csv
          - name: proteomics
            id: syn18689335.3
            format: csv
          - name: agora_proteomics_tmt
            id: syn35221005.2
            format: csv
          - name: agora_proteomics_srm
            id: syn52579640.3
            format: csv
          - name: rna_expression_change
            id: syn27211942.1
            format: tsv
          - name: target_list
            id: syn12540368.41
            format: csv
          - name: median_expression
            id: syn27211878.2
            format: csv
          - name: druggability
            id: syn13363443.11
            format: csv
          - name: genes_biodomains
            id: syn44151254.1
            format: csv
          - name: tep_adi_info
            id: syn51942280.2
            format: csv
        final_format: json
        custom_transformations:
          adjusted_p_value_threshold: 0.05
          protein_level_threshold: 0.05
        column_rename:
          ensg: ensembl_gene_id
          ensembl_id: ensembl_gene_id
          geneid: ensembl_gene_id
          has_eqtl: is_eqtl
          minimumlogcpm: min
          quartile1logcpm: first_quartile
          medianlogcpm: median
          meanlogcpm: mean
          quartile3logcpm: third_quartile
          maximumlogcpm: max
          possible_replacement: ensembl_possible_replacements
          permalink: ensembl_permalink
        provenance:
          - syn25953363.6
          - syn12514826.5
          - syn12514912.3
          - syn18689335.3
          - syn35221005.2
          - syn52579640.3
          - syn27211942.1
          - syn12540368.41
          - syn27211878.2
          - syn13363443.11
          - syn44151254.1
          - syn51942280.2
        agora_rename:
          symbol: hgnc_symbol
        destination: *dest

    - team_info:
        files:
          - name: team_info
            id: syn12615624.16
            format: csv
          - name: team_member_info
            id: syn12615633.16
            format: csv
        final_format: json
        custom_transformations: 1
        provenance:
          - syn12615624.16
          - syn12615633.16
        destination: *dest

    - overall_scores:
        files:
          - name: overall_scores
            id: syn25575156.13
            format: table
        final_format: json
        custom_transformations: 1
        column_rename:
          genename: hgnc_gene_id
        provenance:
          - syn25575156.13
        agora_rename:
          ensg: ensembl_gene_id
          hgnc_gene_id: hgnc_symbol
          geneticsscore: genetics_score
          overall: target_risk_score
          omicsscore: multi_omics_score
        destination: *dest

    - network:
        files:
          - name: networks
            id: syn11685347.1
            format: csv
        final_format: json
        provenance:
          - syn11685347.1
          - syn27211942.1
        agora_rename:
          genea_ensembl_gene_id: geneA_ensembl_gene_id
          genea_external_gene_name: geneA_external_gene_name
          geneb_ensembl_gene_id: geneB_ensembl_gene_id
          geneb_external_gene_name: geneB_external_gene_name
          brainregion: brainRegion
        destination: *dest

    - rnaseq_differential_expression:
        files:
          - name: diff_exp_data
            id: syn27211942.1
            format: tsv
        final_format: json
        custom_transformations: 1
        provenance:
          - syn27211942.1
        destination: *dest

    - distribution_data:
        files:
          - name: overall_scores
            id: syn25575156.13
            format: table
        final_format: json
        custom_transformations:
          overall_max_score: 5
          genetics_max_score: 3
          omics_max_score: 2
        provenance:
          - syn25575156.13
        column_rename:
          overall: target_risk_score
          geneticsscore: genetics_score
          omicsscore: multi_omics_score
        destination: *dest

    - rna_distribution_data:
        files:
          - name: diff_exp_data
            id: syn27211942.1
            format: tsv
        final_format: json
        custom_transformations: 1
        provenance:
          - syn27211942.1
        destination: *dest

    - proteomics_distribution_data:
        files:
          - name: proteomics
            id: syn18689335.3
            format: csv
          - name: proteomics_tmt
            id: syn35221005.2
            format: csv
          - name: proteomics_srm
            id: syn52579640.3
            format: csv
        final_format: json
        custom_transformations: 1
        provenance:
          - syn18689335.3
          - syn35221005.2
          - syn52579640.3
        destination: *dest
