[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta:__legacy__"

[tool.interrogate]
verbose = true
fail-under = 85
ignore-module = true
ignore-nested-functions = true
