- destination: syn25905764
- datasets:
  - network:
      files:
        - syn25905783: json
      final_format: json
      custom_transformations: 1
      provenance:
        - syn25905783
      destination: syn26868906