- destination: syn27406021
- datasets:
  - distribution_data:
      files:
        - syn25575156: table
      final_format: json
      custom_transformations: 1
      provenance:
        - syn25575156
      destination: syn27406021

  - gene_metadata:
      files:
        - syn25953363: feather  # gene_info
        - syn12514826: csv      # igap
        - syn12514912: csv      # eqtl
        - syn18689335: csv      # proteomics
        - syn14237651: tsv      # rna_expression_change
      final_format: json
      custom_transformations:
        adjusted_p_value_threshold: 0.05
        protein_level_threshold: 0.05
      provenance:
        - syn25953363
        - syn12514826
        - syn12514912
        - syn18689335
        - syn11914808
        - syn14237651
      destination: syn17015333

  - gene_info:
      files:
        - syn26868788: json # gene_metadata
        - syn12540368: csv # target_list
        - syn12514804: csv # median_expression
        - syn13363443: csv # drugability
      final_format: json
      custom_transformations: 1
      provenance:
        - syn26868788
        - syn12540368
        - syn12514804
        - syn13363443
      agora_rename:
        eqtl: haseqtl
        igap: isIGAP
        protein_in_ad_brain_change: isAnyProteinChangedInADBrain
        rna_in_ad_brain_change: isAnyRNAChangedInADBrain
        median_expression: medianexpression
        nominated_target: nominatedtarget
      destination: syn17015333

  - genetics_scores:
      files:
        - syn25575153: table
      final_format: json
      provenance:
        - syn25575153
      column_rename:
        ensg: ensenbl_gene_id
        gene_name: hgnc_gene_id
      destination: syn17015333

  - neuropath_corr:
      files:
        - syn22017882: csv
      final_format: json
      provenance:
        - syn22017882
      column_rename:
        ensg: ensembl_gene_id
        gname: hgnc_gene_id
      agora_rename:
        ensembl_gene_id: ensg
        hgnc_gene_id: gname
      destination: syn17015333

  - omics_scores:
      files:
        - syn22758536: table
      final_format: json
      provenance:
        - syn22758536
      destination: syn17015333

  - proteomics:
      files:
        - syn18689335: csv
      final_format: json
      provenance:
        - syn18689335
      column_rename:
        genename: hgnc_gene_id
        ensg: ensemble_gene_id
      agora_rename:
        ensemble_gene_id: ensembl_gene_id
        hgnc_gene_id: hgnc_symbol
      destination: syn17015333

  - target_exp_validation_harmonized:
      files:
        - syn24184512: csv
      final_format: json
      provenance:
        - syn24184512
      destination: syn17015333

  - srm_data:
      files:
        - syn25454540: csv
      final_format: json
      provenance:
        - syn25454540
      destination: syn17015333

  - team_info:
      files:
        - syn12615624: csv
        - syn12615633: csv
      final_format: json
      custom_transformations: 1
      provenance:
        - syn12615624
        - syn12615633
      destination: syn17015333

  - overall_scores:
      files:
        - syn25575156: table
      final_format: json
      custom_transformations: 1
      column_rename:
        genename: hgnc_gene_id
      provenance:
        - syn25575156
        - syn25575153
        - syn22758536
      agora_rename:
        ensg: ENSG
        hgnc_gene_id: GeneName
        geneticsscore: GeneticsScore
        literaturescore: LiteratureScore
        overall: Logsdon
        omicsscore: OmicsScore
      destination: syn17015333

  - rnaseq_differential_expression:
      files:
        - syn14237651: tsv
        - syn25953363: feather
        - syn12540368: csv
        - syn12514912: csv
      final_format: json
      custom_transformations:
        models_to_keep:
          - Diagnosis AD-CONTROL ALL
          - Diagnosis.AOD AD-CONTROL ALL
          - Diagnosis.Sex AD-CONTROL FEMALE
          - Diagnosis.Sex AD-CONTROL MALE
        adjusted_p_value_threshold: 1
      provenance:
        - syn14237651
        - syn25953363
        - syn12540368
        - syn12514912
      destination: syn17015333

  - metabolomics:
      files:
        - syn26064497: feather
      final_format: json
      provenance:
        - syn19001410
        - syn26064497
      destination: syn17015333

  - network:
      files:
        - syn11685347: csv
        - syn25953363: feather
      final_format: json
      custom_transformations: 1
      provenance:
        - syn11685347
        - syn25953363
        - syn14237651
      agora_rename:
        genea_ensembl_gene_id: geneA_ensembl_gene_id
        genea_external_gene_name: geneA_external_gene_name
        geneb_ensembl_gene_id: geneB_ensembl_gene_id
        geneb_external_gene_name: geneB_external_gene_name
        brainregion: brainRegion
      destination: syn17015333